name: Deploy to Fasthosts

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FASTHOSTS_FTP_SERVER }}
          username: ${{ secrets.FASTHOSTS_FTP_USERNAME }}
          password: ${{ secrets.FASTHOSTS_FTP_PASSWORD }}
          protocol: ftps
          server-dir: ${{ secrets.FASTHOSTS_FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.github/**/*
